### ISSUE TITLE
Did you have any plans to add code highlight feature?

### ISSUE THREAD

**Issue by lianghanzhen** [mattvh/solar-theme-ghost#2]
It is a beautiful theme for ghost, greate job! Did you have any plans to add code highlight feature?

**Comment by lianghanzhen** [comment]
I have tried to add it by myself, but it looks wired.

**Comment by mattvh** [comment]
Thanks for reminding me. I had been meaning to get around to that. Just pushed a new release (1.1.0) that adds Prism.js support.

![Screenshot](http://i.imgur.com/yKQqTz1.png)
